### ISSUE TITLE
Livox nodelet not publishing topics

### ISSUE THREAD

**Issue by eborghi10** [oxin-ros/livox_ros_driver#10]
Topics are not published with `roslaunch livox_ros_driver livox_lidar_nodelet.launch`.

Related to #8 because it needs some changes introduced there.

----

Working branch: https://github.com/oxin-ros/livox_ros_driver/tree/hotfix/livox-nodelet-pub

EDIT: There seems to be a problem with the version of GCC: https://github.com/ros/diagnostics/issues/119#issuecomment-1027169155

**Comment by 0x-a6** [comment]
Related to #5
